import { z } from "zod";

export const vehicleFormSchema = z.object({
  stockNumber: z.string().min(1, "Stock number is required"),
  make: z.string().min(1, "Make is required"),
  model: z.string().min(1, "Model is required"),
  trim: z.string().min(1, "Trim is required"),
  year: z.number().min(1990).max(2027),
  condition: z.enum(["new", "used", "certified_pre_owned"]),
  status: z.enum([
    "available",
    "reserved",
    "sold",
    "purchased",
    "in_transit",
    "under_inspection",
    "under_repair",
    "archived",
  ]),
  price: z.number().min(1, "Price is required"),
  costPrice: z.number().min(1, "Cost price is required"),
  repairCost: z.number().min(0),
  transportCost: z.number().min(0),
  expectedSellingPrice: z.number().min(0),
  estimatedMarketValue: z.number().min(0),
  mileageKm: z.number().min(0),
  horsepower: z.number().min(0),
  fuelType: z.enum(["petrol", "diesel", "hybrid", "electric"]),
  transmission: z.enum(["automatic", "manual"]),
  exteriorColor: z.string().min(1, "Required"),
  interiorColor: z.string().min(1, "Required"),
  seats: z.number().min(1).max(12),
  bodyType: z.string().min(1, "Required"),
  vin: z.string().min(5, "VIN is required"),
  importSpec: z.enum(["GCC", "UAE", "Imported"]),
  accidentHistory: z.enum(["none", "minor", "major"]),
  serviceHistory: z.enum(["full", "partial", "none"]),
  owners: z.number().min(0),
  location: z.string().min(1, "Required"),
  emirate: z.enum(["dubai", "abu_dhabi", "sharjah", "ajman", "ras_al_khaimah", "fujairah", "umm_al_quwain"]),
  sourceType: z.enum(["export", "import", "auction", "dealer", "private"]),
  registrationStatus: z.enum(["registered", "not_registered", "pending_transfer"]),
  plateNumber: z.string().optional(),
  registrationExpiryDate: z.string().optional(),
  rtaNotes: z.string().optional(),
  notes: z.string().optional(),
});

export type VehicleFormValues = z.infer<typeof vehicleFormSchema>;
